### ISSUE TITLE
Add Message

### ISSUE THREAD

**Issue by luketlancaster** [nss-evening-cohort-12/chatty-epsilon-hitchhiker#14]
## User Story
As a user, I should be able to add messages by clicking enter.

## AC
**Given** A user navigates to your page
**Then** they type in the input field
**And** when they hit enter a new message should be created
**And** the message should show up in the new chat window

## Dev Notes
(blocked by #4)
* A new object should be created that will be pushed into the `messages[]` array:
```js
{
  timestamp: (timestamp),
  sender: (user id),
  text: (message text),
}
```
* update message window with `printToDom()` function

**Comment by nswalters** [comment]
This depends on #8 being complete.
