### ISSUE TITLE
Clear Messages

### ISSUE THREAD

**Issue by luketlancaster** [nss-evening-cohort-12/chatty-epsilon-hitchhiker#15]
## User Story
As a user, when I have messages, I should be able to clear them out with a single button.

As a user, when I DON'T have messages, I should not be able to click the clear button

## AC
**Given** A user navigates to your page
**Then** they see a bunch of messages
**And** they click the clear button
**And** the chat history should get cleared out

**Given** A user navigates to your page
**And** they see no messages
**Then** the clear button should be disabled.

## Dev Notes
* Each user should have a variable called `trashBefore` which will contain the time they press `clear all` (defaults to `0`)
* On page load, check to see if there are any messages in `messages[]` after the `trashBefore` date, and if so make `clear all` button available and display messages
* When the user presses `clear all` update `trashBefore` to the current timestamp and update the display

**Comment by nswalters** [comment]
Potential future enhancement we thought of during discussion of this enhancement:

**_Allow users to hide individual messages._**

When a user selects to hide an individual message, the `id` of that message would then be stored in a `hiddenMessages` array in that user's profile.  When the page would be refreshed, messages with that `id` would not show up in the history.
