### ISSUE TITLE
Large Text

### ISSUE THREAD

**Issue by luketlancaster** [nss-evening-cohort-12/chatty-epsilon-hitchhiker#16]
## User Story
As a user, with tired eyes, I should be able to chat with large text.

## AC
**Given** A user navigates to your page
**Then** they should see a checkbox below the input field called "Large Text"
**And** they should be able to click this checkbox
**And** when the checkbox is selected all the message text should be larger

## Dev Notes
* Create checkbox and attach event listener, jQuery optional
* Use mix-in to change size of text on page
* Use Roboto font:
` @import url('https://fonts.googleapis.com/css2?family=Roboto&display=swap');`

**Comment by nswalters** [comment]
This doesn't seem to be working properly.  While it changes the font size of the input text box, it doesn't change the font size of the previous messages.

As I understood this enhancement, I should be able to increase the font size of _all_ messages (for readability purposes).  Was this decided to not be the case?

**Comment by nswalters** [comment]
Closed by #45! :D
