### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by luketlancaster** [nss-evening-cohort-12/chatty-epsilon-hitchhiker#2]
## User Story
As a user, when I navigate to your site, I should see a navbar.

## AC
**Given** A user navigates to your page
**Then** they should see a navbar
**And** it should have an application logo
~~**And** it should have an input field~~ Not required per Project Manager (Matt Gill)
~~**And** it should have a clear button~~ Not required per Project Manager (Matt Gill)
**And** it should remain at the top of the screen if the page scrolls

## Dev Notes
* use bootsrap's navbar with brand code with the following graphic :
```html
<nav class="navbar sticky-top navbar-light bg-light">
  <a class="navbar-brand" href="#">
    <img src="" alt="">
  </a>
</nav>
```
[https://getbootstrap.com/docs/4.0/components/navbar/](https://getbootstrap.com/docs/4.0/components/navbar/)

* Logo: ![image](https://user-images.githubusercontent.com/62906411/84097912-7e430c80-a9cb-11ea-8237-caab522a4366.png)

**Comment by nswalters** [comment]
Removed requirements for input field and clear button from navbar per @mtgill.
