### ISSUE TITLE
Timestamps

### ISSUE THREAD

**Issue by luketlancaster** [nss-evening-cohort-12/chatty-epsilon-hitchhiker#9]
## User Story
As a user, using all the chatting sites, I always see clean looking timestamps.

**Dirty Timestamp:**  2014-09-08T08:02:17-05:00
**Clean Timestamp:**  September 8, 2014 8:02 PM

## AC
**Given** A user navigates to your page
**Then** they see all the messages
**And**  the messages should have nice looking timestamps

## Dev Notes
* Real JS developers hate dates - they use a magical library called [MomentJS](https://momentjs.com/)
```js
npm install moment --save
```
* (do that ^)

**Comment by nswalters** [comment]
To get the proper formatted timestamp, you would use the following code, after installing moment.js:

```js
moment().format('MMMM D, YYYY h:mm A');  // Outputs: June 9, 2020 8:25 PM
```

**Comment by nswalters** [comment]
![Screen Shot 2020-06-11 at 6 17 04 PM](https://user-images.githubusercontent.com/10491407/84448259-c3578080-ac0f-11ea-8066-10aba0cfd76a.png)
